### ISSUE TITLE
App not booting up

### ISSUE THREAD

**Issue by hythm7** [ufobat/VoteImproved#1]
Getting this error when trying to start the app
```
bailador watch bin/VoteImproved.p6 
Attempting to boot up the app
! ===SORRY!=== Error while compiling /tmp/VoteImproved/lib/VoteImproved.pm6 (VoteImproved)
Undeclared routine:
    container used at line 11
```
```
$perl6 --version
This is Rakudo version 2017.07-132-gabf1cfe72 built on MoarVM version 2017.07-318-g604da4d0
```
```
$ bailador version
Bailador 0.0.10
```
```
IoC:ver<0.0.1>
```

**Comment by ufobat** [comment]
Bailador needs to be at 0.0.12 in order to Support IoC based routes, i think.

I am using Bailador "dev" because sometimes I ve added things to bailador that I had missed. 

If you need more help let meine know

**Comment by hythm7** [comment]
Thank you. I installed Bailador:ver('0.0.12') and it worked.
